name: CI-CD

on:
  push:
      branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.1.0

    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PWD}}
    
    - name: Construção da imagem Docker
    uses: docker/build-push-action@v3.2.0
    with: 
      context: ./src
      file: ./src/Dockerfile
      push: true
      tags: |
        fabricioveronez/live-kube-news:v1
        fabricioveronez/live-kube-news:latest
